# Generated by Django 5.1.2 on 2024-10-30 01:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_category', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(max_length=120, upload_to='media/')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modification', models.DateField(default=datetime.date.today)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('etat', models.CharField(choices=[('encours', 'En cours de validation'), ('publié', 'publié'), ('rejeté', 'rejeté')], max_length=30)),
                ('nombre_vue', models.IntegerField(default=0, editable=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('auteur', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blogapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('corps', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.article')),
            ],
        ),
    ]
