# Generated by Django 5.1.2 on 2024-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_article_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='corps',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
