# Generated by Django 5.1.2 on 2024-11-01 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_comment_username_comment_auteur_com'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auteur_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
